name: Update Profile

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate-snake-game-gif
        uses: Platane/snk@v0.0.18
        with:
          # github user name
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/snake.gif

      - name: generate-snake-game-gif
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          # github user name
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
